### ISSUE TITLE
frappe.exceptions.DuplicateEntryError: ('Renovation DocField', 'Data Import Legacy-amended_from', IntegrityError(1062, "Duplicate entry 'Data Import Legacy-amended_from' for key 'PRIMARY'"))

### ISSUE THREAD

**Issue by mymi14s** [leam-tech/renovation-core#19]
During Installation, one migration is complete, it ends with a Duplicate Entry error log.
I by passed by reruning migrate

Updating DocTypes for renovation_core: [===================
Updating DocTypes for renovation_core: [===================
Updating DocTypes for renovation_core: [========================================]                                     Supervisor config file updated to use renovation_core.app.application and renovation_core/socketio.js                 Procfile updated to use renovation_core/socketio.js        You may have to restart bench to complete configuration    Traceback (most recent call last):                           File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 320, in db_insert                      frappe.db.sql("""INSERT INTO `tab{doctype}` ({columns})  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 156, in sql                              self._cursor.execute(query, values)                      File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute               result = self._query(query)                              File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query                conn.query(q)                                            File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query             self._affected_rows = self._read_query_result(unbuffered=unbuffered)                                                File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result                                                           result.read()                                            File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read             first_packet = self.connection._read_packet()            File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet      packet.check_error()                                     File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error          err.raise_mysql_exception(self._data)                    File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception     raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'Data Import Legacy-amended_from' for key 'PRIMARY'")
During handling of the above exception, another exception occurred:
Traceback (most recent call last):                           File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main                                                    return _run_code(code, main_globals, None,               File "/usr/lib/python3.8/runpy.py", line 85, in _run_code    exec(code, run_globals)                                  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>                         main()                                                   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main                             click.Group(commands=commands)(prog_name='bench')        File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 764, in __call__                   return self.main(*args, **kwargs)                        File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 717, in main                       rv = self.invoke(ctx)                                    File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke                    return _process_result(sub_ctx.command.invoke(sub_ctx))  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke                    return _process_result(sub_ctx.command.invoke(sub_ctx))  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 956, in invoke                     return ctx.invoke(self.callback, **ctx.params)           File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 555, in invoke                     return callback(*args, **kwargs)                         File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func              return f(get_current_context(), *args, **kwargs)         File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 26, in _func                             ret = f(frappe._dict(ctx.obj), *args, **kwargs)          File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 203, in install_app                          _install_app(app, verbose=context.verbose)               File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 93, in install_app                               frappe.get_attr(after_install)()                         File "/home/frappe/frappe-bench/apps/renovation_core/renovation_core/install/after_install.py", line 11, in after_install
add_all_reqd_table_fields()                              File "/home/frappe/frappe-bench/apps/renovation_core/renovation_core/renovation_core/doctype/renovation_docfield/renovation_docfield.py", line 112, in add_all_reqd_table_fields                                                              doc.insert()                                             File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 248, in insert                              raise e                                                  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 245, in insert                              self.db_insert()                                         File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 335, in db_insert                      raise frappe.DuplicateEntryError(self.doctype, self.name, e)                                                      frappe.exceptions.DuplicateEntryError: ('Renovation DocField', 'Data Import Legacy-amended_from', IntegrityError(1062, "Duplicate entry 'Data Import Legacy-amended_from' for key 'PRIMARY'"))

**Comment by MalikZu** [comment]
Thank you for your feedback! 

This repo is for frontend, can you please use leam-tech/renovation_core to report this issue there?
